# Generated by Django 5.2.6 on 2025-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_job_options_company_alter_job_company_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('full-time', 'Full-time'), ('contract', 'Contract'), ('part-time', 'Part-time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('KES', 'KES'), ('NGN', 'NGN')], max_length=10, null=True),
        ),
    ]
